/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AppData, Subject } from '../types';

export interface ValidationResult {
  success: boolean;
  type?: 'course_design' | 'full_backup';
  data?: AppData;
  error?: string;
}

export function validateAndParseImport(jsonString: string): ValidationResult {
  if (!jsonString || !jsonString.trim()) {
    return { success: false, error: 'Empty import content.' };
  }

  let parsed: any;
  try {
    parsed = JSON.parse(jsonString);
  } catch (e: any) {
    return {
      success: false,
      error: `Malformed JSON string: ${e.message || 'Syntax Error'}. Please check for missing commas or quotes.`,
    };
  }

  if (typeof parsed !== 'object' || parsed === null) {
    return { success: false, error: 'Invalid JSON format. Expected a JSON object at the root level.' };
  }

  // Schema Version Check
  if (parsed.schemaVersion !== undefined) {
    const version = Number(parsed.schemaVersion);
    if (Number.isNaN(version)) {
      return { success: false, error: 'Invalid schemaVersion: must be a number.' };
    }
    if (version > 1) {
      return {
        success: false,
        error: `Unsupported schema version (${version}). This backup/design was generated by a newer version of the app.`,
      };
    }
  }

  // Validate Subjects map
  if (!parsed.subjects || typeof parsed.subjects !== 'object' || Array.isArray(parsed.subjects)) {
    return { success: false, error: 'Missing or invalid "subjects" field. Expected a dictionary/object.' };
  }

  const subjectsKeys = Object.keys(parsed.subjects);
  if (subjectsKeys.length === 0) {
    return { success: false, error: 'The imported course design has no subjects configured.' };
  }

  let hasBacklogField = false;
  const validatedSubjects: Record<string, Subject> = {};

  for (const name of subjectsKeys) {
    const trimmedName = name.trim();
    if (!trimmedName) {
      return { success: false, error: 'Subject names cannot be empty.' };
    }

    const sub = parsed.subjects[name];
    if (typeof sub !== 'object' || sub === null) {
      return { success: false, error: `Subject "${trimmedName}" is invalid. Expected an object.` };
    }

    // Emoji check
    let emoji = '📚';
    if (sub.emoji !== undefined) {
      if (typeof sub.emoji !== 'string') {
        return { success: false, error: `Subject "${trimmedName}" has an invalid emoji. Expected a string.` };
      }
      emoji = sub.emoji.trim() || '📚';
      if (emoji.length > 15) {
        emoji = emoji.substring(0, 15);
      }
    }

    // Color check
    let color = '#ba68c8';
    if (sub.color !== undefined) {
      if (typeof sub.color !== 'string') {
        return { success: false, error: `Subject "${trimmedName}" has an invalid color code. Expected a string.` };
      }
      color = sub.color.trim() || '#ba68c8';
    }

    // Daily growth check
    let daily_increase = 1;
    if (sub.daily_increase !== undefined) {
      const parsedGrowth = Number(sub.daily_increase);
      if (Number.isNaN(parsedGrowth) || parsedGrowth < 0) {
        return { success: false, error: `Subject "${trimmedName}" has an invalid daily_increase value. Must be a non-negative number.` };
      }
      daily_increase = parsedGrowth;
    }

    // Backlog check
    let backlog = 0;
    if (sub.backlog !== undefined) {
      hasBacklogField = true;
      const parsedBacklog = Number(sub.backlog);
      if (Number.isNaN(parsedBacklog) || parsedBacklog < 0) {
        return { success: false, error: `Subject "${trimmedName}" has an invalid backlog value. Must be a non-negative number.` };
      }
      backlog = parsedBacklog;
    }

    validatedSubjects[trimmedName] = {
      name: trimmedName,
      emoji,
      color,
      daily_increase,
      backlog,
    };
  }

  // Detect Type
  // If we have any backlog field or last_updated at the root, treat it as a full backup.
  // Otherwise, it is a course design.
  const isFullBackup = hasBacklogField || parsed.last_updated !== undefined || parsed.setup_done !== undefined;
  const exportType = isFullBackup ? 'full_backup' : 'course_design';

  // Validate general configuration fields
  const courseName = typeof parsed.course_name === 'string' && parsed.course_name.trim()
    ? parsed.course_name.trim()
    : (typeof parsed.title === 'string' && parsed.title.trim() ? parsed.title.trim() : 'Imported Course');

  const classesPerDay = parsed.classes_per_day !== undefined
    ? Math.max(1, Number(parsed.classes_per_day) || 4)
    : 4;

  const skipSunday = parsed.skip_sunday !== undefined
    ? Boolean(parsed.skip_sunday)
    : true;

  const theme = parsed.theme === 'light' || parsed.theme === 'dark'
    ? parsed.theme
    : 'dark';

  const palette_color = typeof parsed.palette_color === 'string' && parsed.palette_color.startsWith('#')
    ? parsed.palette_color
    : undefined;

  // Clean data object
  const cleanData: AppData = {
    subjects: validatedSubjects,
    classes_per_day: classesPerDay,
    skip_sunday: skipSunday,
    course_name: courseName,
    last_updated: typeof parsed.last_updated === 'string' ? parsed.last_updated : new Date().toISOString().split('T')[0],
    setup_done: isFullBackup ? (parsed.setup_done !== undefined ? Boolean(parsed.setup_done) : true) : false,
    theme: theme,
    palette_color: palette_color,
  };

  // If Course Design, clear backlog properties back to 0 just in case
  if (!isFullBackup) {
    Object.keys(cleanData.subjects).forEach(key => {
      cleanData.subjects[key].backlog = 0;
    });
  }

  return {
    success: true,
    type: exportType,
    data: cleanData,
  };
}
